#!/usr/bin/env node

require('reflect-metadata')
const tsConfigPaths = require('tsconfig-paths')
const sourceMapSupport = require('source-map-support')

const { existsSync } = require('fs')
const { Path } = require('@secjs/utils')
const { Ignite } = require('@athenna/core/src/Ignite')
const { Exec } = require('@athenna/artisan/src/Utils/Exec')

async function main() {
  sourceMapSupport.install()
  tsConfigPaths.register({
    baseUrl: './dist',
    paths: {
      ...require('./tsconfig.json').paths,
      ...require('@athenna/core/_tsconfig.json').paths,
    },
  })

  const tscPath = Path.noBuild().pwd('node_modules/.bin/tsc')
  const rimrafPath = Path.noBuild().pwd('node_modules/.bin/rimraf')

  if (process.argv[2] !== 'build' || !existsSync(Path.noBuild().pwd('dist'))) {
    await Exec.command(`${rimrafPath} dist && ${tscPath}`, true)
  }

  process.env.BOOT_LOGS = 'false'

  const application = await new Ignite(__filename + '.js').fire()
  const artisan = await application.bootArtisan()

  await artisan.main('Artisan')
}

main().catch()
