#!/bin/bash

# This file is useful for development purposes because
# it allows you to run TypeScript files without having
# to add the --loader option every time.

# Usage:

# ./node --version
# ./node artisan --version
# ./node bin/main.ts

# Usage with "sh" or "bash":

# sh node --version
# sh node artisan --version
# sh node bin/main.ts

# Node.js executable with all arguments required to run the application.
node="node --loader ts-node/esm --experimental-import-meta-resolve --no-warnings"

# Convert the first "artisan" argument to the "boostrap/artisan.ts" file path.
$node $(echo $@ | sed -e "s/artisan/bin\/artisan.ts/")
