name: CI

on:
  push:
    branches:
      - http
  pull_request:
    branches:
      - http

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.13.1
          - 18.x
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:coverage

      - name: Test code compilation
        run: npm run build

      - name: Run application using compiled code
        run: cp .github/ci.js build/bootstrap/ci.js && node --experimental-import-meta-resolve build/bootstrap/ci.js

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version:
          - 16.13.1
          - 18.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:coverage

      - name: Test code compilation
        run: npm run build

      - name: Run application using compiled code
        run: cp .github/ci.js build/bootstrap/ci.js && node --experimental-import-meta-resolve build/bootstrap/ci.js
